language: python
python:
  - 3.5
install:
  - pip install numpy
  - pip install scipy
  - pip install tensorflow
  - pip install keras
  - pip install gym
script: python main.py -env CartPole-v0 -eps 5