language: python
python:
  - 3.5
before_install:
  - wget "http://eva.fit.vutbr.cz/~xbucha02/log.out"
install: 
  - pip install -r requirements.txt
  - pip install gym[atari]
  - git clone https://github.com/rgal/gym-2048
  - cd gym-2048
  - pip install -e .
  - cd ..
script: python tests.py -v
